## Security Routes
default:
    pattern:   /
    defaults:  { _controller: CodekoLoginPrincipalBundle:Security:login }

login:
    pattern:   /login
    defaults:  { _controller: CodekoLoginPrincipalBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern: /logout
    
profile:
    pattern:   /profile
    defaults:  { _controller: CodekoLoginPrincipalBundle:Profile:show }
    
