_login:
    pattern:  /
    defaults: {_controller: AcmeUserBundle:Security:login }
    
_principal:
    pattern:    /principal
    defaults:  { _controller: AcmeUserBundle:Principal:principal }
    
_registro:
    pattern:    /registro
    defaults:  { _controller: AcmeUserBundle:Registro:registro }

_assetic:
    resource: .
    type:     assetic

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
