codeko_login_principal:
    resource: "@CodekoLoginPrincipalBundle/Controller/"
    type: annotation
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
## Security Routes
default:
    pattern:   /
    defaults:  { _controller: CodekoLoginPrincipalBundle:Security:login }

login:
    pattern:   /login
    defaults:  { _controller: CodekoLoginPrincipalBundle:Security:login }

registro:
    pattern:   /registro
    defaults:  { _controller: CodekoLoginPrincipalBundle:Registro:registro }
    
login_check:
    pattern:   /login_check

principal:
    pattern:    /principal
    defaults:  { _controller: CodekoLoginPrincipalBundle:Principal:principal }
    
profile:
    pattern:    /profile
    defaults:  { _controller: CodekoLoginPrincipalBundle:Profile:show }

logout:
    pattern: /logout  
  
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

# REVISAR ROUTING PROFILE
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@CodekoLoginPrincipalBundle/Resources/config/registration.xml"
    prefix: /registro

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
profile_edit:
    pattern:    /profile/edit
    defaults:  { _controller: CodekoLoginPrincipalBundle:Profile:edit }