_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
#_acme_demo:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

_login_principal:
    resource: "@AcmeLoginPrincipalBundle/Resources/config/routing.yml"

_login:
    pattern:  /
    defaults: {_controller: AcmeLoginPrincipalBundle:Security:login }
    
_principal:
    pattern:    /principal
    defaults:  { _controller: AcmeLoginPrincipalBundle:Principal:principal }
    
_registro:
    pattern:    /registro
    defaults:  { _controller: AcmeLoginPrincipalBundle:Registro:registro }

_assetic:
    resource: .
    type:     assetic