sonata_admin:
    
#    options:
#        html5_validate: false 
        # does not use html5 validation
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extend global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig       
        
 #   security:
        #handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display two dashboard blocks             
            -
                position: left
                class: col-md-12
                type: sonata.admin.block.admin_list
                
            -   
                position: right
                type: sonata.timeline.block.timeline
                settings: 
                    context: SONATA_ADMIN
                    max_per_page: 10                          
                                
        groups:
            Users:
                label: Usuarios
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                roles: [ROLE_SUPER_ADMIN ]
                
            Password Manager:
                label: Password Manager
                items:
                    - password.pass.servicio
                    - sonata.classification.admin.category
                    - application_sonata_user.admin.tipo_pass
                    - sonata.media.admin.media
                roles: [ROLE_USER]
                
    options:
        use_select2:    true 
        # disable select2
       
        